{{- /*  For all clusterroles defined */}}
{{- range $clusterRoleKey, $clusterRoleObject := $.Values.vaultInit.clusterRoleBindings }}
{{- /*  if ServiceAccounts are defined */}}
{{- if $clusterRoleObject.serviceAccounts }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: "rbac-{{ $clusterRoleKey }}-sa"
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: "{{ $clusterRoleKey }}"
subjects:

{{- /*  For all ServiceAccount */}}
{{- range $entityKey, $entityValues := $clusterRoleObject }}
{{- range $entityValues }}
- kind: ServiceAccount
  namespace: {{ (split ":" .)._0 | quote }}
  name: {{ (split ":" .)._1 | quote }}
{{- end }}
{{- end }}

{{- end }}
{{- end }}

---

{{- if .Values.eso.enabled -}}
{{- range $clusterRoleKey, $clusterRoleObject := $.Values.eso.clusterRoleBindings }}
{{- /*  if ServiceAccounts are defined */}}
{{- if $clusterRoleObject.serviceAccounts }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: "rbac-{{ $clusterRoleKey }}-sa"
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: "{{ $clusterRoleKey }}"
subjects:

{{- /*  For all ServiceAccount */}}
{{- range $entityKey, $entityValues := $clusterRoleObject }}
{{- range $entityValues }}
- kind: ServiceAccount
  namespace: {{ (split ":" .)._0 | quote }}
  name: {{ (split ":" .)._1 | quote }}
{{- end }}
{{- end }}

{{- end }}
{{- end }}
{{- end }}

---

{{- if .Values.eso.enabled -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: role-tokenreview-binding-eso
  namespace: {{ .Values.eso.namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:auth-delegator
subjects:
  - kind: ServiceAccount
    name: {{ .Values.eso.saName }}
    namespace: {{ .Values.eso.namespace }}
{{- end }}