{{- range $roleKey, $roleObject := .Values.vaultInit.clusterRoles }}
---
{{- /*  Define a ClusterRole 'rolename */}}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: "{{ $roleKey }}"
rules:
{{- /*  Iterate over rules */}}
{{- range $roleObject }}
- {{- toYaml . | nindent 2 }}
{{- end }}
{{- end }}

---


{{- if .Values.eso.enabled -}}
{{- range $roleKey, $roleObject := .Values.eso.clusterRoles }}
---
{{- /*  Define a ClusterRole 'rolename */}}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: "{{ $roleKey }}"
rules:
{{- /*  Iterate over rules */}}
{{- range $roleObject }}
- {{- toYaml . | nindent 2 }}
{{- end }}
{{- end }}
{{- end }}