apiVersion: batch/v1
kind: Job
metadata:
  name: {{ .Chart.Name }}-init
  annotations:
    "helm.sh/hook": post-install
    "helm.sh/hook-weight": "1"
    "helm.sh/hook-delete-policy": before-hook-creation, hook-succeeded
spec:
  template:
    spec:
      serviceAccountName: {{ .Values.vaultInit.serviceAccount.name | quote }}
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
      containers:
      - image: "{{ .Values.vaultInit.image.repository }}:{{ .Values.vaultInit.image.tag }}"
        imagePullPolicy: {{ .Values.vaultInit.image.imagePullPolicy }}
        name: {{ .Chart.Name }}-init
        command: ["sh", "-c", "./vault-init.sh"]
        env:
        - name: LEADER_VAULT_ADDRESS
          value: "http://vault-0.vault-internal.{{ .Release.Namespace }}:8200"
        - name: LEADER_SECRET_THRESHOLD
          value: "3"
        - name: LEADER_SECRET_SHARES
          value: "5"
        - name: SECRET_NAME
          value: "{{ .Chart.Name }}-init-secrets"
        securityContext:
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"
      restartPolicy: OnFailure
  backoffLimit: 5
