{{- /* For all namespaces defined */}}
{{- range $namespaceKey, $namespaceObject := .Values.vaultInit.roleBindings }}
{{- /*  For all roles defined in each namespace */}}
{{- range $roleKey, $roleObject := $namespaceObject }}
{{- /*  if ServiceAccounts are defined */}}
{{- if $roleObject.serviceAccounts }}
---
{{- /*  Define a RoleBinding 'namespace'-'role'-sa */}}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: "{{ $namespaceKey }}-{{ $roleKey }}-sa"
  namespace: "{{ $namespaceKey }}"
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: "{{ $roleKey }}"
subjects:
{{- /*  For all subject types (User, Group) */}}
{{- range $entityKey, $entityValues := $roleObject }}
{{- if eq $entityKey "serviceAccounts" }}
{{- range $entityValues }}
- kind: ServiceAccount
  namespace: {{ (split ":" .)._0 | quote }}
  name: {{ (split ":" .)._1 | quote }}
{{- end }}
{{- end }}
{{- end }}

{{- end }}
{{- end }}
{{- end }}

---

{{- if .Values.eso.enabled -}}
{{- /* For all namespaces defined */}}
{{- range $namespaceKey, $namespaceObject := .Values.eso.roleBindings }}
{{- /*  For all roles defined in each namespace */}}
{{- range $roleKey, $roleObject := $namespaceObject }}
{{- /*  if ServiceAccounts are defined */}}
{{- if $roleObject.serviceAccounts }}
---
{{- /*  Define a RoleBinding 'namespace'-'role'-sa */}}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: "{{ $namespaceKey }}-{{ $roleKey }}-sa"
  namespace: "{{ $namespaceKey }}"
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: "{{ $roleKey }}"
subjects:
{{- /*  For all subject types (User, Group) */}}
{{- range $entityKey, $entityValues := $roleObject }}
{{- if eq $entityKey "serviceAccounts" }}
{{- range $entityValues }}
- kind: ServiceAccount
  namespace: {{ (split ":" .)._0 | quote }}
  name: {{ (split ":" .)._1 | quote }}
{{- end }}
{{- end }}
{{- end }}

{{- end }}
{{- end }}
{{- end }}
{{- end }}