apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.vault-init.serviceAccount.name | quote }}
  namespace: {{ .Release.Namespace }}
  annotations:
    "helm.sh/hook": post-install, post-upgrade
    "helm.sh/hook-weight": "-1"
    "helm.sh/hook-delete-policy": before-hook-creation, hook-succeeded
