vault:
  injector:
    enabled: false
  server:
    serviceAccount:
      createSecret: true
    ha:
      enabled: false
      raft:
        enabled: false

vault-init:
  serviceAccount:
    name: "auth-vault-init"

  image:
    repository: "alpacked/vault-init-scripts"
    tag: "0.1.0-rc"
    imagePullPolicy: Always

eso-init:
  # Use only if external-secrets is already deployed
  enabled: false
  namespace: "external-secrets-system"
  serviceAccount:
    name: "auth-eso-init"

  image:
    repository: "alpacked/vault-init-scripts"
    tag: "0.1.0-rc"
    imagePullPolicy: Always
