vault:
  injector:
    enabled: false
  server:
    serviceAccount:
      createSecret: true
    ha:
      enabled: false
      raft:
        enabled: false

image:
  repository: "alpacked/vault-init-scripts"
  tag: "0.1.1-rc"
  imagePullPolicy: Always

esoInit:
  # Use only if external-secrets is already deployed
  enabled: false
  namespace: "external-secrets-system"
  serviceAccount:
    name: "auth-eso-init"
