vault:
  injector:
    enabled: false
  server:
    serviceAccount:
      createSecret: true
    ha:
      enabled: true
      raft:
        enabled: true

vault-init:
  serviceAccount:
    name: "auth-vault-init"

  image:
    repository: "alpacked/vault-init-scripts"
    tag: "0.1.0-rc"
    imagePullPolicy: Always

external-secrets:
  enabled: true
  namespace: "external-secrets-system"

eso-init:
  enabled: true
  namespace: "external-secrets-system"
  serviceAccount:
    name: "auth-eso-init"

  image:
    repository: "alpacked/vault-init-scripts"
    tag: "0.1.0-rc"
    imagePullPolicy: Always
